blog/main/routes.py
from flask import render_template, redirect, flash, url_for, request, Blueprint
from blog.models import database, Post, User
from blog.posts.forms import contact_form
main = Blueprint('main', __name__)


 #Home page for the blog mainlication
@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts=Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('home.html', posts=posts)

#About us

@main.route('/about')
def about():
    return render_template('about.html')

#contact us
@main.route('/contact')
def contact():
    form = contact_form()
    if form.validate_on_submit():
        message_sent = User(first_name=form.first_name.data, email=form.email.data,
                    last_name=form.last_name.data, message=form.message.data)
        database.session.add(message_sent)
        database.session.commit()
        flash('Form submitted successfully', 'successs')
        return redirect(url_for('home'))
    return render_template('contact.html', title='Contact', form=form)

blog/posts/routes.py
from flask import (render_template, redirect, flash, url_for, 
                   abort, request, Blueprint)
from flask_login import current_user, login_required
from blog import database
from blog.models import Post
from blog.posts.forms import Create_post, contact_form
posts = Blueprint('posts', __name__)


#Creating a new post in the  blog application

@posts.route('/post/new', methods=["POST", "GET"])
@login_required
def new_post():
    form = Create_post()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        database.session.add(post)
        database.session.commit()
        flash('Post created Successfully', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', legend='Create New Post',  form=form)


#Edit an existing post with the current user
@posts.route('/post/<int:post_id>')
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('edit_post.html', title=post.title, post=post)


#updating an existing post with the current user
@posts.route('/post/<int:post_id>/update', methods=["POST", "GET"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = Create_post()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        database.session.commit()
        flash('Post Updated Successfully!', 'success')
        return redirect(url_for('main.home', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', legend='Update Post', form=form)

#Delete a post
@posts.route('/post/<int:post_id>/delete', methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    database.session.delete(post)
    database.session.commit()
    flash('Post Deleted Successfully!', 'success')
    return redirect(url_for('main.home'))

blog/users/routes.py
from flask import (render_template, redirect, flash, url_for, 
                   abort, request, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from blog import database, bcrypt
from blog.models import User, Post
from blog.users.forms import (Registration_form, Login_form, Profile_update, Reset_request, Password_reset )
from blog.users.utils import save_profile_pics, reset_email

users = Blueprint('users', __name__)

#Register new users
@users.route("/register", methods=["POST", "GET"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Registration_form()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password = hashed_password)
        database.session.add(user)
        database.session.commit()
        flash('Account Created Successfully, Please log in now!' ,'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


#Authenticate and log users in 
@users.route('/login', methods=["POST", "GET"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home')) 
    form = Login_form()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data )
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check Email and Password', 'danger')
    return render_template('login.html', title='Login', form=form)


#Log users out
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


#users profiles update     
@users.route('/profile', methods=["POST", "GET"])
@login_required
def profile():
    form = Profile_update()
    if form.validate_on_submit():
        if form.profile_pics.data:
            picture_file = save_profile_pics(form.profile_pics.data)
            current_user.image_file = picture_file        
        current_user.username = form.username.data
        current_user.email = form.username.data
        database.session.commit()
        flash('Profile Updated Successfully!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_images/' + current_user.image_file)
    return render_template('profile.html', title='Profile', image_file=image_file, form=form)


#Authentication to check numbers of post by a user and pagination
@users.route("/user/<string:username>")
def users_post(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('users_post.html', posts=posts, user=user)


#request token from users when they forget their passwords
@users.route('/reset_password', methods=["POST", "GET"])
def reset_request(): 
    if current_user.is_authenticated:
        return redirect(url_for('home')) 
    form = Reset_request()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        reset_email(user)
        flash('Authentication Email sent', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title ='Reset Password', form=form)

#reset users password
@users.route('/reset_password/<token>', methods=["POST", "GET"])
def reset_token(): 
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.reset_verified_token()
    if user is None:
        flash('Invalid or Expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = Password_reset()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        database.session.commit()
        flash('Password Changed Successfully, Please log in now!' ,'success')
        return redirect(url_for('users.login')) 
    return render_template('reset_token.html', title ='Reset Password', form=form)
    

blog/templates/about.html
{% extends 'base.html' %}


{% block content %}

<legend>About Us</legend>

<div class="card">
    <div class="card-header">
        Our Vision
    </div>
    <div class="card-body">
        <h5 class="card-title">What we Stand for:</h5>
        <p class="card-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard
        dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen
        book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially
        unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more
        recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      
    </div>
</div> <br>

<div class="card">
    <div class="card-header">
        Mission
    </div>
    <div class="card-body">
        <h5 class="card-title">Our Mission:</h5>
        <p class="card-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
            been the industry's standard
            dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
            type specimen
            book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining
            essentially
            unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum
            passages, and more
            recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        
    </div>
</div>



{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}

    <title>Blog App {{ title }}</title>
    {% else %}
    <title>Blog App</title>

    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">AltSchool Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{url_for('main.home')}}">Home</a>
                        <a class="nav-item nav-link" href="{{url_for('main.about')}}">About Us</a>
                        <a class="nav-item nav-link" href="{{url_for('main.contact')}}">Contact Us</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        
                        {% if current_user.is_authenticated %}
                        <a href="{{url_for('posts.new_post')}}" class="nav-item nav-link">Create New Post</a>
                            <a href="{{url_for('users.profile')}}" class="nav-item nav-link">Profile</a>
                            <a href="{{url_for('users.logout')}}" class="nav-item nav-link">Logout</a>                            
                        {% else %}                            
                            <a href="{{url_for('users.login')}}" class="nav-item nav-link">Login</a>
                            <a href="{{url_for('users.register')}}" class="nav-item nav-link">Register</a>                    
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                
                {% with messages = get_flashed_messages(with_categories=true)  %}
                    
                    {% if messages %}
                        
                        {% for category, message in messages  %}
                        
                            <div class="alert alert-{{ category }}">
                                {{ message }}
                            </div>

                        {% endfor %}                            
                        
                    {% endif %}
                        
                {% endwith %}
                    
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4" >
                <div class="content-section" style="background-color: black; color:white;">                    
                    <h3 style="color:white;">Updates</h3>
                    <p class='text-muted'>
                    <ul class="list-group" >
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        
                    </ul>
                    <!-- <img src="{{ url_for('static', filename='demo/teacher.jgp') }}" alt=""> -->
                    </p>                    
                </div>                
            </div>
        </div>

    </main>

    </div><br><br>

    <div class="card text-center" style="background-color: black; color:white;">
        <div class="card-header">
            Alt School Africa Blog Project
        </div>
        <div class="card-body">
            <h5 class="card-title">Updates</h5>
            <p class="card-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <a href="{{url_for('main.home')}}" class="nav-item nav-link" style="color: white;">Home</a>
            <a href="{{url_for('main.about')}}" class="nav-item nav-link" style="color: white;">About Us</a>
            <a href="{{url_for('main.contact')}}" class="nav-item nav-link" style="color: white;">Contact Us</a>
        </div>
        <div class="card-footer text-muted">
            @2022
        </div>
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>





</body>

</html>

blog/templates/contact.html
{% extends 'base.html' %}


{% block content %}

<div class="content-section" style="background-color: black; color:white;">
    <form action="#" method="POST">

        {{ form.hidden_tag() }}
        
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Let's hear from You:</legend>

            <div class="form-group">
                {{form.first_name.label(class='form-control-label')}}

                {% if form.first_name.errors %}

                {{form.first_name(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.first_name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.first_name(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.last_name.label(class='form-control-label')}}
            
                {% if form.last_name.errors %}
            
                {{form.last_name(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
            
                    {% for error in form.last_name.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.last_name(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.email.label(class='form-control-label')}}

                {% if form.email.errors %}

                {{form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.message.label(class='form-control-label')}}
            
                {% if form.message.errors %}
            
                {{form.message(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">
            
                    {% for error in form.message.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.message(class='form-control form-control-lg')}}
                {% endif %}
            </div>

          

        </fieldset>

        <div class="form-group" style="color: white;">
            {{form.submit(class='btn btn-light')}}
        </div>

    </form>
</div>

{% endblock content %}

blog/templates/create_post.html
{% extends 'base.html' %}


{% block content %}

<div class="content-section" style="background-color: black; color:white;">
    <form action="#" method="POST">

        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{legend}}</legend>

            <div class="form-group">
                {{form.title.label(class='form-control-label')}}

                {% if form.title.errors %}

                {{form.title(class='form-control form-control-lg is-invalid')}}
                <div class="invatitlelid-feedback">

                    {% for error in form.title.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.content.label(class='form-control-label' ) }}

                {% if form.content.errors %}

                {{form.content(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.content.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class='form-control form-control-lg')}}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{form.submit(class='btn btn-light')}}
        </div>
    </form>
</div>

{% endblock content %}

blog/templates/edit_post.html
{% extends 'base.html' %}


{% block content %}

<article class="media content-section">
    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}" alt="">
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.users_post', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>

            <!-- Checking if current_users is login before Updating or Deleting a Post -->
            {% if post.author == current_user %}

                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id)}}">Update Post</a>

                    <button class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete Post</button>
                </div>
                
            {% endif %}
                
        </div>
        <h2 class="article-title"> {{ post.title }} </h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="deleteModalLabel">Delete Post?</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}


{% block content %}

{% for post in posts.items %}
<article class="media content-section">
    
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}" alt="">
    
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.users_post', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for ('posts.edit_post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}


{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)  %}
    
    {% if page_num %}
        
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}"> {{ page_num }}</a>
        {% endif %} 
        
    {% else %}
        ...

    {% endif %}
        
    
{% endfor %}
    

{% endblock content %}

blog/templates/login.html
{% extends 'base.html' %}


{% block content %}

<div class="content-section">
    <form action="#" method="POST">

        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Login:</legend>

            

            <div class="form-group">
                {{form.email.label(class='form-control-label')}}

                {% if form.email.errors %}

                {{form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>

            <div class="form-group">
                {{form.password.label(class='form-control-label')}}

                {% if form.password.errors %}

                {{form.password(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.password.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                    {{ form.password(class='form-control form-control-lg')}}
                {% endif %}
            </div>
            
            <div class="form-check">
                {{form.remember(class="form-check-input")}}
                {{form.remember.label(class="form-check-label")}}
            </div>
        </fieldset>

        <div class="form-group">
            {{form.submit(class='btn btn-outline-dark')}}
                <small class="text-muted ml-2">
                    <a href="{{url_for('users.reset_request')}}"> Forgot Password? </a>
                </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Don't Have An Account? <a class="ml-2" href="{{url_for('users.register')}}"> Sign Up Now </a>
    </small>
</div>
{% endblock content %}

blog/templates/profile.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ current_user.username }}</h1>

    <div class="content-section" >
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}" alt="Profile Photo"  >
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>

        <!-- FORM TO UPDATE PROFILE  -->
 
            <form action="#" method="POST" enctype="multipart/form-data" >
        
                {{ form.hidden_tag() }}
        
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Profile Info:</legend>
        
                    <div class="form-group">
                        {{form.username.label(class='form-control-label')}}
        
                        {% if form.username.errors %}
        
                        {{form.username(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
        
                            {% for error in form.username.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.username(class='form-control form-control-lg')}}
                        {% endif %}
                    </div>
        
                    <div class="form-group">
                        {{form.email.label(class='form-control-label')}}
        
                        {% if form.email.errors %}
        
                        {{form.email(class='form-control form-control-lg is-invalid')}}
                        <div class="invalid-feedback">
        
                            {% for error in form.email.errors %}
                            <span>{{error}}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class='form-control form-control-lg')}}
                        {% endif %}
                    </div>     
                    
                    <div class="form-group">
                        {{ form.profile_pics.label() }}
                        {{ form.profile_pics( class='form-control-file') }}
                        
                        {% if form.profile_pics.errors %}

                            {% for error in form.profile_pics.errors %}
                                <span class="text-danger">{{error}}</span> </br>
                            {% endfor %}
                            
                        {% endif %}
                            
                    </div>
                </fieldset>
        
                <div class="form-group">
                    {{form.submit(class='btn btn-outline-dark')}}
                </div>
        
            </form> 
    </div>

{% endblock content %}

blog/templates/reset_request.html
{% extends 'base.html' %}


{% block content %}

<div class="content-section">
    <form action="#" method="POST">

        {{ form.hidden_tag() }}

        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password:</legend>

            <div class="form-group">
                {{form.email.label(class='form-control-label')}}

                {% if form.email.errors %}

                {{form.email(class='form-control form-control-lg is-invalid')}}
                <div class="invalid-feedback">

                    {% for error in form.email.errors %}
                    <span>{{error}}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class='form-control form-control-lg')}}
                {% endif %}
            </div>
        </fieldset>

        <div class="form-group">
            {{form.submit(class='btn btn-outline-info')}}
        </div>
    </form>
</div>
{% endblock content %}

blog/templates/users_post.html
{% extends 'base.html' %}


{% block content %}

<h1 class="mb-3"> Posts by {{user.username}} ({{posts.total}})</h1>

{% for post in posts.items %}
<article class="media content-section">

    <img class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_images/' + post.author.image_file) }}" alt="">

    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.users_post', username=post.author.username)}}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2><a class="article-title" href="{{ url_for ('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %}


{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

{% if page_num %}

{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.users_post', username=user.username,  page=page_num) }}"> {{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('users.users_post', username=user.username, page=page_num) }}"> {{ page_num }}</a>
{% endif %}

{% else %}
...

{% endif %}


{% endfor %}


{% endblock content %}